### PR TITLE
Fix: AfterFeature is called as many times as there are scenarios that throw an exception in AfterScenario

### LINKED ISSUE #526: AfterFeature is called as many times as there are scenarios that throw an exception in AfterScenario.
### Reqnroll Version

2.4

### Which test runner are you using?

NUnit

### Test Runner Version Number

5.0.0

### .NET Implementation

.NET Framework 4.8.0

### Test Execution Method

Visual Studio Test Explorer, Resharper, NUnit.Console-3.19.2

### Content of reqnroll.json configuration file

_No response_

### Issue Description
If the related AfterScenario method with tag has exception (eg. from an Assert), then the AfterFeature method with tag is called as many time as many scenario affected
a) I use Reqnroll.ExternalData with @DataSorce tag. I have CSV file for the data.
b) Scenario Outline
c) Scenario

### Steps to Reproduce

Create the project
Run the test. Scenarios a), b), c) (see Issue description) verified separetlied

[ReqnrollTemplateProject1.zip](https://github.com/user-attachments/files/19206962/ReqnrollTemplateProject1.zip)

Test output:

=> ReqnrollTemplateProject1.Features.CalculatorFeature.AddTwoNumbers("firstData",null)
Given the first number is 50
The first number is 50
-> done: CalculatorStepDefinitions.GivenTheFirstNumberIs(50) (0.0s)
=> ReqnrollTemplateProject1.Features.CalculatorFeature.AddTwoNumbers("secondData",null)
Given the first number is 50
The first number is 50
-> done: CalculatorStepDefinitions.GivenTheFirstNumberIs(50) (0.0s)
=> ReqnrollTemplateProject1.Features.CalculatorFeature.AddTwoNumbers("thirdData",null)
Given the first number is 50
The first number is 50
-> done: CalculatorStepDefinitions.GivenTheFirstNumberIs(50) (0.0s)
=> ReqnrollTemplateProject1_NUnitAssemblyHooks
-> Loading plugin C:\Projects\ReqnrollTemplateProject1\ReqnrollTemplateProject1\bin\Debug\net48\Reqnroll.NUnit.ReqnrollPlugin.dll
-> Loading plugin C:\Projects\ReqnrollTemplateProject1\ReqnrollTemplateProject1\bin\Debug\net48\ReqnrollTemplateProject1.dll
-> Using default config
AfterFeature is called
AfterFeature is called
AfterFeature is called
-> warning: Found 3 not released TestRunners (ids: 2,4,3)

see: https://github.com/zsbolgar/ReqnrollTemplateProject1/blob/master/DataSourceWithAfterFeature.txt

### Link to Repro Project
https://github.com/zsbolgar/ReqnrollTemplateProject1
_No response_

### PR DESCRIPTION
**Pull request by gasparnagy**
### 🤔 What's changed?

Made sure that every relevant code after a hook call is in a finally block or somehow else ensured that it runs even in a case of a hook error.

### ⚡️ What's your motivation? 

Fixes #526 

### 🏷️ What kind of change is this?

- :bug: Bug fix (non-breaking change which fixes a defect)

### ♻️ Anything particular you want feedback on?

This issue was introduced in v2.2.0 with support scenario-level (method-level) parallel execution (#119, #277).

### 📋 Checklist:

- [ ] I've changed the behaviour of the code
  - [x] I have added/updated tests to cover my changes.
- [x] Users should know about my change
  - [ ] I have added an entry to the "[vNext]" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request & included my GitHub handle to the release contributors list.

----

*This text was originally taken from the [template of the Cucumber project](https://github.com/cucumber/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md), then edited by hand. [You can modify the template here.](https://github.com/reqnroll/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

File: Reqnroll.Generator/Generation/UnitTestFeatureGenerator.cs [hunk 1]
```diff
@@ -252,9 +253,20 @@ private void SetupTestInitializeMethod(TestClassGenerationContext generationCont
                 nameof(ITestRunner.OnFeatureEndAsync));
             _codeDomHelper.MarkCodeMethodInvokeExpressionAsAwait(onFeatureEndAsyncExpression);
 
-            //if (testRunner.FeatureContext != null && !testRunner.FeatureContext.FeatureInfo.Equals(featureInfo))
-            //  await testRunner.OnFeatureEndAsync(); // finish if different
-            testInitializeMethod.Statements.Add(
+            // VB does not allow the use of the await keyword in a "finally" clause. Therefore, we have to generate code specific to
+            // the language. The C# code will await OnFeatureStartAsync() while VB will call is sync and assign a variable to the resulting Task.
```
Comment (clrudolphi) [inline Reqnroll.Generator/Generation/UnitTestFeatureGenerator.cs:257]: Suggest minor change to the comment to clarify meaning:
The C# code will await OnFeatureStartAsync() while the VB code will call it synchronously and assign a variable to the resulting Task.

File: Reqnroll.Generator/Generation/UnitTestFeatureGenerator.cs [hunk 2]
```diff
@@ -272,29 +284,79 @@ private void SetupTestInitializeMethod(TestClassGenerationContext generationCont
...
                         new CodePrimitiveExpression(null)),
-                    new CodeExpressionStatement(
-                        onFeatureStartExpression)));
+                    onFeatureStartExpression);
+
+            testInitializeMethod.Statements.Add(
+                new CodeTryCatchFinallyStatement(
+                    [conditionallyExecuteOnFeatureEndExpressionStatement],
+                    [],
+                    [conditionallyExecuteFeatureStartExpressionStatement, throwErrorOnPreviousFeatureStartError]));
```
Comment (clrudolphi) [inline Reqnroll.Generator/Generation/UnitTestFeatureGenerator.cs:347]: How will throwErrorOnPreviouslFeatureStartError interact with VB generated code? This will throw an exception after a Task has been created, but not yet awaited upon (which is after the Finally clause).

File: Reqnroll.Generator/Generation/UnitTestFeatureGenerator.cs (hunk 1 above)
Comment (gasparnagy) [reply Reqnroll.Generator/Generation/UnitTestFeatureGenerator.cs:257]: I'm not fully sure if this VB structure work at all. If the try block will throw an exception, the finally will save the Task (and runs the sync part of it up until the first async op) but then the exception will be propagated, so the await on the task variable will never run. Or do I miss something?

File: Reqnroll.Generator/Generation/UnitTestFeatureGenerator.cs (hunk 2 above)
Comment (clrudolphi) [reply Reqnroll.Generator/Generation/UnitTestFeatureGenerator.cs]: Moved the throwErrorOnPreviousFeatureStartError up above the invocation of the FeatureStart.
I believe a truth-table for what we want as an outcome is the following. Let me know if you think otherwise:
| FeatureContext Instance| BeforeFeatureHookFailed| OnFeatureStartThrows| Scenario is Executed?|
|--------|--------|--------|--------|
| Null|  not checked | FALSE| Yes|
| Null|  not checked | TRUE| No|
| Not Null| FALSE| FALSE| Yes|
| Not Null| FALSE| TRUE| No|
| Not Null| TRUE| FALSE| No| 
| Not Null| TRUE| TRUE| No|

Comment (gasparnagy) [reply Reqnroll.Generator/Generation/UnitTestFeatureGenerator.cs]: The decision table is even simpler, because the `OnFeatureStart` is only relevant for the first scenario execution of a feature (FeatureContext is null), while the BeforeFeatureHookFailed is an indicator for the subsequent scenario executions of the same feature (FeatureContext is not null). So the table is:

| FeatureContext Instance| BeforeFeatureHookFailed| OnFeatureStartThrows| Scenario is Executed?|
|--------|--------|--------|--------|
| Null (first scenario of feature) |  not checked | FALSE| Yes|
| Null  (first scenario of feature) |  not checked | TRUE| No|
| Not Null (further scenario in feature) | FALSE| OnFeatureStart not executed | Yes|
| Not Null (further scenario in feature) | TRUE| OnFeatureStart not executed | No|

File: Reqnroll.Generator/Generation/UnitTestFeatureGenerator.cs (hunk 1 above)
Comment (gasparnagy) [reply Reqnroll.Generator/Generation/UnitTestFeatureGenerator.cs]: I have improved the comment.

**Review by clrudolphi — APPROVED** [review]
