### PR TITLE
Fix Reqnroll.Microsoft.Extensions.DependencyInjection is searching in the wrong assemblies

### LINKED ISSUE #477: [ScenarioDependencies] in a project without StepBindings gives 'No method marked with [ScenarioDependencies] attribute found' (Reqnroll.Microsoft.Extensions.DependencyInjection)
### Reqnroll Version

2.3 Reqnroll.Microsoft.Extensions.DependencyInjection

### Which test runner are you using?

NUnit

### .NET Implementation

.NET 8.0

### Test Execution Method

ReSharper Test Runner

### Content of reqnroll.json configuration file

```json
{
  "$schema": "https://schemas.reqnroll.net/reqnroll-config-latest.json",
  "bindingAssemblies": [
    {
      "assembly": "Project1"
    },
    {
      "assembly": "Project2"
    }
  ]
}
```

### Issue Description

`[ScenarioDependencies]` in a project without stepdefinitions (e.g. `[Given]`, `[When]`) can't find the `[ScenarioDependencies]` method

This is with Microsoft.Extensions.DependencyInjection, I haven't checked the other plugins (autofac etc)

### Steps to Reproduce

Given in reqnroll.json:

```json
  "bindingAssemblies": [
    {
      "assembly": "Project1"
    },
    {
      "assembly": "Project2"
    }
  ]
```

In Project1 are stepdefinitions. In Project2 is the `[ScenarioDependencies]`

Then the  `[ScenarioDependencies]` can't be found:
> Reqnroll.Microsoft.Extensions.DependencyInjection.MissingScenarioDependenciesException : No method marked with [ScenarioDependencies] attribute found.

The issue is in 
https://github.com/reqnroll/Reqnroll/blob/966d1c372bdef843d7a2e3ecd267e07722351d80/Plugins/Reqnroll.Autofac.ReqnrollPlugin/BindingRegistryExtensions.cs#L20C2-L25C10

called by https://github.com/reqnroll/Reqnroll/blob/966d1c372bdef843d7a2e3ecd267e07722351d80/Plugins/Reqnroll.Microsoft.Extensions.DependencyInjection.ReqnrollPlugin/ServiceCollectionFinder.cs#L27

as this will get the assemblies from the stepdefinitions, while I assumed this would loop the assemblies from reqnroll.json

### Link to Repro Project

_No response_

related #474

### PR DESCRIPTION
**Pull request by 304NotModified**
### 🤔 What's changed?
The plugin should search in the bindingAssemblies. Not in the "assemblies that has stepdefinitions" 

Used `ITestRunnerManager`, removed unneeded class

I also added a happy path test. We could use that pattern to fix also #474 

update: added some more tests for this plugin and the ServiceCollectionFinder

### ⚡️ What's your motivation? 

Fixes #477  

### 🏷️ What kind of change is this?

- :bug: Bug fix (non-breaking change which fixes a defect)

### ♻️ Anything particular you want feedback on?

I think we need `ITestRunnerManager` as discussed before, but would be nice if we could publish a pre-release package

### 📋 Checklist:

- [x] I've changed the behaviour of the code
  - [x] I have added/updated tests to cover my changes.
- [x] Users should know about my change
  - [x] I have added an entry to the "[vNext]" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request & included my GitHub handle to the release contributors list.

----

*This text was originally taken from the [template of the Cucumber project](https://github.com/cucumber/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md), then edited by hand. [You can modify the template here.](https://github.com/reqnroll/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by 304NotModified** [comment]
I'm confused by this message. There are no merge commits?
image

File: Plugins/Reqnroll.Microsoft.Extensions.DependencyInjection.ReqnrollPlugin/BindingRegistryExtensions.cs [hunk 1]
```diff
@@ -1,27 +0,0 @@
-﻿using System.Collections.Generic;
-using System.Linq;
-using System.Reflection;
-using Reqnroll.Bindings;
-using Reqnroll.Bindings.Reflection;
-
-namespace Reqnroll.Microsoft.Extensions.DependencyInjection
```
Comment (304NotModified) [inline Plugins/Reqnroll.Microsoft.Extensions.DependencyInjection.ReqnrollPlugin/BindingRegistryExtensions.cs:7]: FYI, not needed anymore! Nice!

**Comment by gasparnagy** [comment]
Looks good. Does that also mean that the new model should also search for the configuration class in all binding assemblies?

**Comment by 304NotModified** [comment]
yes, it very likely that the [ScenarioDependencies] is not living in the same project/assembly as the [Binding]s

**Comment by 304NotModified** [comment]
yes this works, tested it with the following configurations:

image

image

The old work around still works, but now no need for 
```c#
/// <summary>
/// Needed for [ScenarioDependencies] in this assembly
/// </summary>
[Binding]
public class FakeBinding
{
    [Given("Not an operation")]
    public static void Noop()
    {
        //NOOP
    }
}
```

**Review by gasparnagy — APPROVED** [review]
Nice, thx!

**Comment by gasparnagy** [comment]
@304NotModified Thank you for the contribution! According to our [guidelines](https://github.com/orgs/reqnroll/discussions/67) I have invited you to the Reqnroll [contributors team](https://github.com/orgs/reqnroll/teams/contributors/members). Congrats! 🎉 If you accept it, you will be able to make pull requests easier in the future.

You are also welcome on our discord server: https://go.reqnroll.net/discord-invite
