### PR TITLE
Capture ExecutionContext after every binding invoke

### LINKED ISSUE #120: Execution Context (AsyncLocal) does not get transferred between [BeforeScenario] and the steps.
### Reqnroll Version

1.0.1

### Which test runner are you using?

xUnit

### Test Runner Version Number

2.6.5

### .NET Implementation

.NET 8.0

### Test Execution Method

ReSharper Test Runner

### Content of reqnroll.json configuration file

_No response_

### Issue Description

I have a setup in our tests where we have a service provider which generates services, and each of our tests is arranged as a separate request (scope). We also have some default value prefilling on before scenario (actual logic is more complex, but for sake of example it can be simplified).

The issue here is when we use IHttpContextAccessor, a singleton service, it internally uses AsyncLocal to keep track of the HTTP context. On Specflow, the assigned context in BeforeScenario, can be seen later in the service, however when using reqnroll, it cannot.

### Steps to Reproduce

Successful commit (specflow): https://github.com/GedasFX/AsyncLocal_ReqNRoll/commit/99c0c508dff421dbfd0649e09c363aa18c9318ef
Failing commit (reqnroll): https://github.com/GedasFX/AsyncLocal_ReqNRoll/commit/d444e22bc5f45fc4c097999630fff62feea1f343

Checkout the commits. There is a single test in the test suite.

### Link to Repro Project

https://github.com/GedasFX/AsyncLocal_ReqNRoll

### PR DESCRIPTION
**Pull request by obligaron**
Fixes #120

Reqnroll (and Specflow v4,x) uses Async internally (only one code path).
To ensure the user sees no difference between the old (synchronous) implementation and the new ones the `ExecutionContext` (including `AsyncLocal`) are handled manually by Reqnroll.
This is done using `ExecutionContext.Capture()` in `BindingDelegateInvoker,InvokeInExecutionContext`.

The problem is that this only works once.
Background:
- In the first call
  - `ExecutionContextHolder.Value` is null. 
  - This means that `ExecutionContext.Run` is not called.
  - The Binding-Method is called with the current `ExecutionContext` and modifies the `AsyncLocal`. 
  - Current `ExecutionContext` is captured
  -  => everything is fine.
- In the second call
  - `ExecutionContextHolder.Value` is not null.
  - `ExecutionContext.Run` is called.
    - `ExecutionContext.Run` captures the current `ExecutionContext`
    - In `ExecutionContext.Run` the Binding-Method is called and modifies the `AsyncLocal`.
    - The `ExecutionContext.Run` restores the captured "old current" `ExecutionContext` with the old values
  - The current (restored) `ExecutionContext` is captured
  -  => Information is lost.

Bufix: Capture `ExecutionContext` explicitly in `ExecutionContext.Run` after every binding invoke.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Performance improvement
- [ ] Refactoring (so no functional change)
- [ ] Other (docs, build config, etc)

## Checklist:

- [x] I've added tests for my code. (most of the time mandatory)
- [x] I have added an entry to the changelog. (mandatory)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: Reqnroll/Bindings/BindingDelegateInvoker.cs [hunk 1]
```diff
@@ -25,22 +25,31 @@ public virtual async Task<object> InvokeDelegateAsync(Delegate bindingDelegate,
 
             try
```
Comment (gasparnagy) [inline Reqnroll/Bindings/BindingDelegateInvoker.cs:26]: This is a great idea! Basically you have introduced the ExecutionContext capture logic also for the case when the ExecutionContext already exists, because the current solution captures it "too late", it has to be captured **within** the   `ExecutionContext.Run`.

But now, as we have the idea, this can be further simplified, because currently the capture logic is duplicated. What you can do is to undo the changes of `InvokeInExecutionContext` and perform the try-finally logic in the delegate that is passed to that method. So basically we need to move the try-finally one more step inside. So at the end, the `InvokeDelegateAsync` method return statement will look like:

```
            return await InvokeInExecutionContext(executionContext?.Value, () =>
            {
                try
                {
                    return CreateDelegateInvocationTask(bindingDelegate, invokeArgs);
                }
                finally
                {
                    if (executionContext != null)
                        executionContext.Value = ExecutionContext.Capture();
                }
            });
```

I made a quick check locally with your improved unit tests and they pass with this code. Could you please also try?

**Review by gasparnagy — CHANGES_REQUESTED** [review]
The idea and the unit tests are great, I made a suggestion for simplifying the code.

File: Reqnroll/Bindings/BindingDelegateInvoker.cs (hunk 1 above)
Comment (obligaron) [reply Reqnroll/Bindings/BindingDelegateInvoker.cs]: I also tested the suggestions and it looks good to me.
The code is also simpler. Thanks 🙂

**Review by gasparnagy — APPROVED** [review]
Thx!
